services:
  # ==========================
  # FRONTEND - STREAMLIT
  # ==========================
  - type: web
    name: Maduk BI-frontend
    env: python
    plan: free
    buildCommand: |
      cd frontend
      pip install -r requirements.txt
    startCommand: |
      cd frontend
      streamlit run app.py --server.port $PORT --server.address 0.0.0.0

  # ==========================
  # BACKEND - FASTAPI
  # ==========================
  - type: web
    name: Maduk BI-backend
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      uvicorn main:app --host 0.0.0.0 --port $PORT